# Generated by Django 5.0.4 on 2024-05-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenities',
            new_name='Amenity',
        ),
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
    ]
