# Generated by Django 5.0.4 on 2024-05-06 07:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0002_rename_amenities_amenity_alter_amenity_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='location',
        ),
        migrations.AddField(
            model_name='amenity',
            name='point_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='amenity',
            name='polygon_location',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
