# Generated by Django 5.0.4 on 2024-05-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0003_remove_amenity_location_amenity_point_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='type',
            new_name='amenity_type',
        ),
    ]
