# Generated by Django 5.0.4 on 2024-05-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0004_rename_type_amenity_amenity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={},
        ),
        migrations.AddField(
            model_name='amenity',
            name='geom_type',
            field=models.CharField(default='Polygon', max_length=50),
            preserve_default=False,
        ),
    ]
