# Generated by Django 5.0.4 on 2024-05-21 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_unit_lease_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='community',
        ),
        migrations.RemoveField(
            model_name='building',
            name='neighbours',
        ),
    ]
